function(set_number_of_frequencies NEMOH_TEST_PATH N_FREQ)
    file(READ ${NEMOH_TEST_PATH}/Nemoh.cal FILE_CONTENTS)
    string(REGEX REPLACE "([123][ \t]+)[0-9]+([ \t]+[0-9]+\\.?[0-9]*[ \t]+[0-9]+\\.?[0-9]*[ \t]+! ?Freq type)" "\\1${N_FREQ}\\2" FILE_CONTENTS ${FILE_CONTENTS})
    file(WRITE ${NEMOH_TEST_PATH}/Nemoh.cal ${FILE_CONTENTS})

    if(${ARGC} GREATER 2) # If an additional argument is present
        file(READ ${NEMOH_TEST_PATH}/Nemoh.cal FILE_CONTENTS)
        string(REGEX REPLACE "[0-9]+([ \t]+[0-9]+\\.?[0-9]*[ \t]+[0-9]+\\.?[0-9]*[ \t]+! Number of radial frequencies)" "${ARGV2}\\1" FILE_CONTENTS ${FILE_CONTENTS})
        file(WRITE ${NEMOH_TEST_PATH}/Nemoh.cal ${FILE_CONTENTS})
    endif()
endfunction()

add_subdirectory(1_Cylinder)
add_subdirectory(my_Cylinder)

add_subdirectory(BEM_Nb2_dof6_d1)
add_subdirectory(BEM_Nb2_dof1_d1)

add_subdirectory(BEM_Nb2_dof6_d10)
add_subdirectory(BEM_Nb2_dof1_d10)

add_subdirectory(BEM_Nb2_dof6_d100)
add_subdirectory(BEM_Nb2_dof1_d100)

add_subdirectory(BEM_Nb1_dof6)
add_subdirectory(BEM_Nb1_dof1)

add_subdirectory(my_Cylinder_IT/)
add_subdirectory(BEM_Nb2_dof1_d2)
add_subdirectory(BEM_Nb2_dof1_d3)
add_subdirectory(BEM_Nb2_dof1_d4)
add_subdirectory(BEM_Nb2_dof1_d5)
add_subdirectory(BEM_Nb2_dof1_d6)
add_subdirectory(BEM_Nb2_dof1_d7)
add_subdirectory(BEM_Nb2_dof1_d8)
add_subdirectory(BEM_Nb2_dof1_d9)
add_subdirectory(BEM_Nb2_dof1_d15)
add_subdirectory(BEM_Nb2_dof1_d20)
add_subdirectory(BEM_Nb2_dof1_d30)
add_subdirectory(BEM_Nb2_dof1_d40)
add_subdirectory(BEM_Nb2_dof1_d50)
add_subdirectory(BEM_Nb2_dof1_d60)
add_subdirectory(BEM_Nb2_dof1_d70)
add_subdirectory(BEM_Nb2_dof1_d80)
add_subdirectory(BEM_Nb2_dof1_d90)
add_subdirectory(BEM_Nb2_dof1_d150)
add_subdirectory(BEM_Nb2_dof1_d200)
add_subdirectory(BEM_Nb2_dof1_d250)
add_subdirectory(BEM_Nb2_dof1_d300)
add_subdirectory(BEM_Nb2_dof1_d350)
add_subdirectory(BEM_Nb2_dof1_d400)
add_subdirectory(BEM_Nb2_dof1_d450)
add_subdirectory(BEM_Nb2_dof1_d500)
add_subdirectory(BEM_Nb2_dof1_d600)
add_subdirectory(BEM_Nb2_dof1_d700)
add_subdirectory(BEM_Nb2_dof1_d800)
add_subdirectory(BEM_Nb2_dof1_d900)
add_subdirectory(BEM_Nb2_dof1_d1000)
add_subdirectory(BEM_Nb2_dof6_d2)
add_subdirectory(BEM_Nb2_dof6_d3)
add_subdirectory(BEM_Nb2_dof6_d4)
add_subdirectory(BEM_Nb2_dof6_d5)
add_subdirectory(BEM_Nb2_dof6_d6)
add_subdirectory(BEM_Nb2_dof6_d7)
add_subdirectory(BEM_Nb2_dof6_d8)
add_subdirectory(BEM_Nb2_dof6_d9)
add_subdirectory(BEM_Nb2_dof6_d10)
add_subdirectory(BEM_Nb2_dof6_d15/)
add_subdirectory(BEM_Nb2_dof6_d20)
add_subdirectory(BEM_Nb2_dof6_d30)
add_subdirectory(BEM_Nb2_dof6_d40)
add_subdirectory(BEM_Nb2_dof6_d50)
add_subdirectory(BEM_Nb2_dof6_d60)
add_subdirectory(BEM_Nb2_dof6_d70)
add_subdirectory(BEM_Nb2_dof6_d80)
add_subdirectory(BEM_Nb2_dof6_d90)
add_subdirectory(BEM_Nb2_dof6_d100)
add_subdirectory(BEM_Nb2_dof6_d200)
add_subdirectory(BEM_Nb2_dof6_d300)
add_subdirectory(BEM_Nb2_dof6_d400)
add_subdirectory(BEM_Nb2_dof6_d500)
add_subdirectory(BEM_Nb2_dof6_d600)
add_subdirectory(BEM_Nb2_dof6_d700)
add_subdirectory(BEM_Nb2_dof6_d800)
add_subdirectory(BEM_Nb2_dof6_d900)
add_subdirectory(BEM_Nb2_dof6_d1000)
add_subdirectory(BEM_Nb2_dof6_dy1)
add_subdirectory(BEM_Nb2_dof6_dy10)
add_subdirectory(BEM_Nb2_dof6_dy20)
add_subdirectory(BEM_Nb2_dof6_dy30)
add_subdirectory(BEM_Nb2_dof6_dy40)
add_subdirectory(BEM_Nb2_dof6_dy50)
add_subdirectory(BEM_Nb2_dof6_dy60)
add_subdirectory(BEM_Nb2_dof6_dy70)
add_subdirectory(BEM_Nb2_dof6_dy80)
add_subdirectory(BEM_Nb2_dof6_dy90)
add_subdirectory(BEM_Nb2_dof6_dy100)
add_subdirectory(BEM_Nb2_dof6_dy200)
add_subdirectory(BEM_Nb2_dof6_dy300)
add_subdirectory(BEM_Nb2_dof6_dy400)
add_subdirectory(BEM_Nb2_dof6_dy500)
add_subdirectory(BEM_Nb2_dof6_dy600)
add_subdirectory(BEM_Nb2_dof6_dy700)
add_subdirectory(BEM_Nb2_dof6_dy800)
add_subdirectory(BEM_Nb2_dof6_dy900)
add_subdirectory(BEM_Nb2_dof6_dy1000)
add_subdirectory(BEM_Nb2_dof6_dy2000)
add_subdirectory(BEM_Nb2_dof1_dy1)
add_subdirectory(BEM_Nb2_dof1_dy10)
add_subdirectory(BEM_Nb2_dof1_dy20)
add_subdirectory(BEM_Nb2_dof1_dy30)
add_subdirectory(BEM_Nb2_dof1_dy40)
add_subdirectory(BEM_Nb2_dof1_dy50)
add_subdirectory(BEM_Nb2_dof1_dy60)
add_subdirectory(BEM_Nb2_dof1_dy70)
add_subdirectory(BEM_Nb2_dof1_dy80)
add_subdirectory(BEM_Nb2_dof1_dy90)
add_subdirectory(BEM_Nb2_dof1_dy100)
add_subdirectory(BEM_Nb2_dof1_dy200)
add_subdirectory(BEM_Nb2_dof1_dy300)
add_subdirectory(BEM_Nb2_dof1_dy400)
add_subdirectory(BEM_Nb2_dof1_dy500)
add_subdirectory(BEM_Nb2_dof1_dy600)
add_subdirectory(BEM_Nb2_dof1_dy700)
add_subdirectory(BEM_Nb2_dof1_dy800)
add_subdirectory(BEM_Nb2_dof1_dy900)
add_subdirectory(BEM_Nb2_dof1_dy1000)
add_subdirectory(BEM_Nb2_dof1_dy2000)
add_subdirectory(TEST_input)
add_subdirectory(BEM_barge_d1)
add_subdirectory(BEM_barge_d20)
add_subdirectory(BEM_barge_d500)
add_subdirectory(BEM_barge_dof1_d1)
add_subdirectory(BEM_barge_dof1_d20)
add_subdirectory(BEM_barge_dof1_d500)
add_subdirectory(BEM_PBsigne)
add_subdirectory(TEST)
add_subdirectory(BEM_barge_d2)
add_subdirectory(BEM_barge_d4)
add_subdirectory(BEM_barge_d8)
add_subdirectory(BEM_barge_d16)
add_subdirectory(BEM_barge_d32)
add_subdirectory(BEM_barge_d64)
add_subdirectory(BEM_barge_d128)
add_subdirectory(BEM_barge_d256)
add_subdirectory(BEM_barge_d512)
add_subdirectory(BEM_barge_d1024)
add_subdirectory(BEM_barge_d10)
add_subdirectory(BEM_barge_dy1)
add_subdirectory(BEM_barge_dy2)
add_subdirectory(BEM_barge_dy4)
add_subdirectory(BEM_barge_dy8)
add_subdirectory(BEM_barge_dy16)
add_subdirectory(BEM_barge_dy32)
add_subdirectory(BEM_barge_dy64)
add_subdirectory(BEM_barge_dy128)
add_subdirectory(BEM_barge_dy256)
add_subdirectory(BEM_barge_dy512)
add_subdirectory(BEM_barge_dy1024)
add_subdirectory(BEM_barge_Nb3X_d1)
add_subdirectory(BEM_barge_Nb3X_d2)
add_subdirectory(BEM_barge_Nb3X_d4)
add_subdirectory(BEM_barge_Nb3X_d8)
add_subdirectory(BEM_barge_Nb3X_d16)
add_subdirectory(BEM_barge_Nb3X_d32)
add_subdirectory(BEM_barge_Nb3X_d64)
add_subdirectory(BEM_barge_Nb3X_d128)
add_subdirectory(BEM_barge_Nb3X_d256)
add_subdirectory(BEM_barge_Nb3X_d512)
add_subdirectory(BEM_barge_Nb3X_d1024)
add_subdirectory(BEM_barge_Nb3Y_d1)
add_subdirectory(BEM_barge_Nb3Y_d2)
add_subdirectory(BEM_barge_Nb3Y_d3)
add_subdirectory(BEM_barge_Nb3Y_d4)
add_subdirectory(BEM_barge_Nb3Y_d8)
add_subdirectory(BEM_barge_Nb3Y_d16)
add_subdirectory(BEM_barge_Nb3Y_d32)
add_subdirectory(BEM_barge_Nb3Y_d64)
add_subdirectory(BEM_barge_Nb3Y_d128)
add_subdirectory(BEM_barge_Nb3Y_d256)
add_subdirectory(BEM_barge_Nb3Y_d512)
add_subdirectory(BEM_barge_Nb3Y_d1024)
add_subdirectory(BEM_barge_Nb3T_d1)
add_subdirectory(BEM_barge_Nb3T_d2)
add_subdirectory(BEM_barge_Nb3T_d4)
add_subdirectory(BEM_barge_Nb3T_d8)
add_subdirectory(BEM_barge_Nb3T_d16)
add_subdirectory(BEM_barge_Nb3T_d32)
add_subdirectory(BEM_barge_Nb3T_d64)
add_subdirectory(BEM_barge_Nb3T_d128)
add_subdirectory(BEM_barge_Nb3T_d256)
add_subdirectory(BEM_barge_Nb3T_d512)
add_subdirectory(BEM_barge_Nb3T_d1024)
add_subdirectory(BEM_barge_Nb3Tinv_d1)
add_subdirectory(BEM_barge_Nb3Tinv_d2)
add_subdirectory(BEM_barge_Nb3Tinv_d4)
add_subdirectory(BEM_barge_Nb3Tinv_d8)
add_subdirectory(BEM_barge_Nb3Tinv_d16)
add_subdirectory(BEM_barge_Nb3Tinv_d32)
add_subdirectory(BEM_barge_Nb3Tinv_d64)
add_subdirectory(BEM_barge_Nb3Tinv_d128)
add_subdirectory(BEM_barge_Nb3Tinv_d256)
add_subdirectory(BEM_barge_Nb3Tinv_d512)
add_subdirectory(BEM_barge_Nb3Tinv_d1024)
add_subdirectory(PIT3_barge_dof6)
add_subdirectory(BEM_cylinder_Nb2_X_d1)
add_subdirectory(BEM_cylinder_Nb2_X_d2)
add_subdirectory(BEM_cylinder_Nb2_X_d3)
add_subdirectory(BEM_cylinder_Nb2_X_d4)
add_subdirectory(BEM_cylinder_Nb2_X_d8)
add_subdirectory(BEM_cylinder_Nb2_X_d16)
add_subdirectory(BEM_cylinder_Nb2_X_d32)
add_subdirectory(BEM_cylinder_Nb2_X_d64)
add_subdirectory(BEM_cylinder_Nb2_X_d128)
add_subdirectory(BEM_cylinder_Nb2_X_d256)
add_subdirectory(BEM_cylinder_Nb2_X_d512)
add_subdirectory(BEM_cylinder_Nb3_T_d1)
add_subdirectory(BEM_cylinder_Nb3_T_d2)
add_subdirectory(BEM_cylinder_Nb3_T_d4)
add_subdirectory(BEM_cylinder_Nb3_T_d8)
add_subdirectory(BEM_cylinder_Nb3_T_d16)
add_subdirectory(BEM_cylinder_Nb3_T_d32)
add_subdirectory(BEM_cylinder_Nb3_T_d64)
add_subdirectory(BEM_cylinder_Nb3_T_d128)
add_subdirectory(BEM_cylinder_Nb3_T_d256)
add_subdirectory(BEM_cylinder_Nb3_T_d512)
add_subdirectory(BEM_cylinder_Nb4_C_d1)
add_subdirectory(BEM_cylinder_Nb4_C_d2)
add_subdirectory(BEM_cylinder_Nb4_C_d4)
add_subdirectory(BEM_cylinder_Nb4_C_d8)
add_subdirectory(BEM_cylinder_Nb4_C_d16)
add_subdirectory(BEM_cylinder_Nb4_C_d32)
add_subdirectory(BEM_cylinder_Nb4_C_d64)
add_subdirectory(BEM_cylinder_Nb4_C_d128)
add_subdirectory(BEM_cylinder_Nb4_C_d256)
add_subdirectory(BEM_cylinder_Nb4_C_d512)
add_subdirectory(BEM_cylinder_Nb2_X_d126)
add_subdirectory(BEM_test_RAO)
add_subdirectory(BEM_testRAO_d2)
add_subdirectory(BEM_barge_FS)
add_subdirectory(BEM_barge_FS_d1)
add_subdirectory(BEM_barge_FS_d2)
add_subdirectory(BEM_barge_FS_d4)
add_subdirectory(BEM_barge_FS_d8)
add_subdirectory(BEM_barge_FS_d16)
add_subdirectory(BEM_barge_FS_d32)
add_subdirectory(BEM_barge_FS_d64)
add_subdirectory(BEM_barge_FS_d128)
add_subdirectory(BEM_barge_FS_d256)
add_subdirectory(BEM_barge_FS_d1024)
add_subdirectory(REFINING)
add_subdirectory(BEM_barge_FS_d512)
add_subdirectory(BEM_barge_FS_Nb2_X_d64)
add_subdirectory(BEM_barge_FS_Nb2_Y_d64)
add_subdirectory(BEM_barge_FS_Nb2_Y_d1)
add_subdirectory()
add_subdirectory(BEM_FS)
add_subdirectory(BEM_FS_Nb2_Y_d1)
add_subdirectory(BEM_FS_Nb3_Y_d1)
add_subdirectory(BEM_FS_Nb3_X_d1)
add_subdirectory(BEM_FS_Nb3_T_d1)
add_subdirectory(BEM_FS_Nb3_Tinv_d1)
add_subdirectory(BEM_FS_Nb4_C_d1)
add_subdirectory(BEM_cylinderC_Nb2_X_d1)
add_subdirectory(BEM_cylinderC_Nb2_X_d2)
add_subdirectory(BEM_cylinderC_Nb2_X_d4)
add_subdirectory(BEM_cylinderC_Nb2_X_d8)
add_subdirectory(BEM_cylinderC_Nb2_X_d16)
add_subdirectory(BEM_cylinderC_Nb2_X_d32)
add_subdirectory(BEM_cylinderC_Nb2_X_d64)
add_subdirectory(BEM_cylinderC_Nb2_X_d128)
add_subdirectory(BEM_cylinderC_Nb2_X_d256)
add_subdirectory(BEM_cylinderC_Nb2_X_d3)
add_subdirectory(BEM_cylinderC_Nb2_X_d512)
add_subdirectory(BEM_test_Nb4_C_d1)
add_subdirectory(BEM_Hydro_Nb2_X_d16)
add_subdirectory(PIT_Hydro_Nb2_X_d16)
add_subdirectory(PIT_Hydro)
add_subdirectory(BEM_Hydro)
add_subdirectory(BEM_Hydro_16)
