################
#  My Test cases  #
################
# TestCases directory
testdir=.

#NEMOH1 testcases
.PHONY: run_1_cylinder clean_1_cylinder
run_1_cylinder: 
	$(MAKE) -C $(testdir)/1_Cylinder/ run

clean_1_cylinder:
	$(MAKE) -C $(testdir)/1_Cylinder/ clean

.PHONY: run_my_cylinder clean_my_cylinder
run_my_cylinder: 
	$(MAKE) -C $(testdir)/my_Cylinder/ run

clean_my_cylinder:
	$(MAKE) -C $(testdir)/my_Cylinder/ clean

.PHONY: clean_all_tests
clean_all_tests: clean_1_cylinder clean_my_cylinder
	
	
.PHONY: run_BEM_Nb2_dof6_d1 clean_BEM_Nb2_dof6_d1
run_BEM_Nb2_dof6_d1: 
	$(MAKE) -C $(testdir)/BEM_Nb2_dof6_d1/ run

clean_BEM_Nb2_dof6_d1:
	$(MAKE) -C $(testdir)/BEM_Nb2_dof6_d1/ clean
	
.PHONY: run_BEM_Nb2_dof1_d1 clean_BEM_Nb2_dof1_d1
run_BEM_Nb2_dof1_d1: 
	$(MAKE) -C $(testdir)/BEM_Nb2_dof1_d1/ run

clean_BEM_Nb2_dof1_d1:
	$(MAKE) -C $(testdir)/BEM_Nb2_dof1_d1/ clean
	
.PHONY: run_BEM_Nb2_dof6_d10 clean_BEM_Nb2_dof6_d10
run_BEM_Nb2_dof6_d10: 
	$(MAKE) -C $(testdir)/BEM_Nb2_dof6_d10/ run

clean_BEM_Nb2_dof6_d10:
	$(MAKE) -C $(testdir)/BEM_Nb2_dof6_d10/ clean
	
.PHONY: run_BEM_Nb2_dof1_d10 clean_BEM_Nb2_dof1_d10
run_BEM_Nb2_dof1_d10: 
	$(MAKE) -C $(testdir)/BEM_Nb2_dof1_d10/ run

clean_BEM_Nb2_dof1_d10:
	$(MAKE) -C $(testdir)/BEM_Nb2_dof1_d10/ clean
	
.PHONY: run_BEM_Nb2_dof6_d100 clean_BEM_Nb2_dof6_d100
run_BEM_Nb2_dof6_d100: 
	$(MAKE) -C $(testdir)/BEM_Nb2_dof6_d100/ run

clean_BEM_Nb2_dof6_d100:
	$(MAKE) -C $(testdir)/BEM_Nb2_dof6_d100/ clean
	
.PHONY: run_BEM_Nb2_dof1_d100 clean_BEM_Nb2_dof1_d100
run_BEM_Nb2_dof1_d100: 
	$(MAKE) -C $(testdir)/BEM_Nb2_dof1_d100/ run

clean_BEM_Nb2_dof1_d100:
	$(MAKE) -C $(testdir)/BEM_Nb2_dof1_d100/ clean
	
.PHONY: run_BEM_Nb1_dof1 clean_BEM_Nb1_dof1
run_BEM_Nb1_dof1: 
	$(MAKE) -C $(testdir)/BEM_Nb1_dof1/ run

clean_BEM_Nb1_dof1:
	$(MAKE) -C $(testdir)/BEM_Nb1_dof1/ clean




